version: '3.3'

services:

  app-shortener:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'arco-tech-url-shortener'
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html


  db-shortener:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: 'arco-tech-url-shortener'
      MYSQL_ROOT_PASSWORD: "arcotech"
