version: '3.3'

services:

  appshortener:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'arcourl'
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html


  dbshortener:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'arcourl'
      MYSQL_ROOT_PASSWORD: "arco"
